### ISSUE TITLE
Joypad support

### ISSUE THREAD

**Issue by inactive123** [r-type/libretro-nuklear-soft#1]
Great project!

I was already testing this out in the CAP32 core, I'm wondering if there is any joypad support though? So far I haven't been able to control the GUI with it.

I think as soon as we have gamepad support we could have an ideal GUI to use for home computer-based cores.

**Comment by r-type** [comment]
yes joypad is working for control gui . but by default is turn off (MOUSE_EMULATED flag)
i had implemented them in frodo and cap32 port  (although in a bad hacky way ).  
this repo is outdated , i ll update with the last update i did in cap32.

**Comment by r-type** [comment]
there is also an ogl libretro implementation 
https://github.com/r-type/nuklear/tree/master/demo/libretro_opengl

**Comment by r-type** [comment]
I've updated to v1.18 and add support for Joypad to emulate mouse.
By default real mouse , you can toggle with hitting RETRO_DEVICE_ID_JOYPAD_SELECT.

@twinaphex , i have some Libretro related questions
is possible for the core to get some info from the frontend like is fullscreen? is mousegrab , max resolution supported . something like core get capabilities... if not , Is it hard to implement?

i want for example , the core can draw mouse pointer if in fullscreen or mouse grabbed .

**Comment by inactive123** [comment]
Well, all that information (like 'is fullscreen', 'max resolutions supported', etc) - it would all be highly frontend-specific. If we were to add that now, nothing but RetroArch would be able to make use of it. I think that would be a bad idea.

I could add environment callbacks indicating if the mouse is grabbed or something, that seems reasonable at least.

**Comment by r-type** [comment]
you are right , I forget each time  other frontend !
environment callbacks to query mouse grabb /fullscreen state will be nice.

**Comment by r-type** [comment]
close as basic joypad support in done.
